# Generated by Django 4.0.4 on 2022-10-31 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainScheme',
            fields=[
                ('scheme_name', models.CharField(help_text='physics-4a-scheme-2020', max_length=40, primary_key=True, serialize=False)),
                ('subject_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Subjects.masomo')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SchemeOfWork',
            fields=[
                ('id', models.CharField(auto_created=True, default=uuid.uuid4, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('serial_no', models.CharField(blank=True, max_length=20, null=True)),
                ('competence', models.TextField(blank=True, null=True)),
                ('objectives', models.TextField(blank=True, null=True)),
                ('month', models.CharField(blank=True, max_length=20, null=True)),
                ('week', models.CharField(blank=True, help_text='namba ya wiki', max_length=2, null=True)),
                ('main_topic', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_topic', models.TextField(blank=True, null=True)),
                ('periods', models.CharField(blank=True, max_length=2, null=True)),
                ('teaching_activities', models.TextField(blank=True, null=True)),
                ('learning_activities', models.TextField(blank=True, null=True)),
                ('references', models.TextField(blank=True, null=True)),
                ('teaching_aids', models.TextField(blank=True, null=True)),
                ('assesments', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('scheme_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SchemeOfWork.mainscheme')),
            ],
        ),
    ]
