# Generated by Django 4.0.4 on 2022-10-31 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Student', '0001_initial'),
        ('Subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolTplan',
            fields=[
                ('id', models.CharField(help_text='kiswa-lp-t1-2022', max_length=40, primary_key=True, serialize=False)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Subjects.masomo')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tplan',
            fields=[
                ('lesson_id', models.CharField(help_text='lesson01-term1-2021', max_length=30, primary_key=True, serialize=False)),
                ('class_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Student.madarasa')),
                ('school_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessondevelopment.schooltplan')),
            ],
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(blank=True, help_text='number of period', max_length=10, null=True)),
                ('time', models.CharField(blank=True, help_text='example 4hrs', max_length=10, null=True)),
                ('boy_registered', models.CharField(blank=True, max_length=10, null=True)),
                ('girls_registered', models.CharField(blank=True, max_length=10, null=True)),
                ('boy_present', models.CharField(blank=True, max_length=10, null=True)),
                ('girls_present', models.CharField(blank=True, max_length=10, null=True)),
                ('competence', models.CharField(blank=True, max_length=400, null=True)),
                ('topic', models.CharField(blank=True, max_length=400, null=True)),
                ('sub_topic', models.TextField(blank=True, max_length=400, null=True)),
                ('general_objectives', models.TextField(blank=True, max_length=700, null=True)),
                ('specific_objectives', models.TextField(blank=True, max_length=1000, null=True)),
                ('T_learning_materials', models.TextField(blank=True, max_length=1000, null=True)),
                ('reference', models.TextField(blank=True, max_length=500, null=True)),
                ('lesson_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessondevelopment.tplan')),
            ],
        ),
        migrations.CreateModel(
            name='LessonEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_eval', models.TextField(blank=True, null=True)),
                ('teacher_eval', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('lesson_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessondevelopment.tplan')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson_development',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(blank=True, choices=[('introduction', 'introduction'), ('developing new knowledge', 'developing new knowledge'), ('reinforcement', 'reinforcement'), ('reflection', 'reflection'), ('consolidation', 'consolidation')], default='introduction', max_length=30, null=True)),
                ('time', models.CharField(blank=True, help_text='example 4hrs', max_length=10, null=True)),
                ('teaching_activities', models.TextField(blank=True, null=True)),
                ('learning_activities', models.TextField(blank=True, null=True)),
                ('assesment', models.TextField(blank=True, null=True)),
                ('lesson_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessondevelopment.tplan')),
            ],
        ),
    ]
