# Generated by Django 4.0.4 on 2022-10-31 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogBookSerial',
            fields=[
                ('log_name', models.CharField(help_text='physics-4a-log-2020', max_length=100, primary_key=True, serialize=False)),
                ('subject_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Subjects.masomo')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Logbook',
            fields=[
                ('id', models.CharField(auto_created=True, default=uuid.uuid4, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('sno', models.CharField(default='01', max_length=4)),
                ('week_no', models.CharField(blank=True, max_length=2, null=True)),
                ('month_no', models.CharField(blank=True, max_length=2, null=True)),
                ('main_topic', models.TextField(blank=True, max_length=200, null=True)),
                ('sub_topic', models.TextField(blank=True, max_length=200, null=True)),
                ('time_start', models.DateField(blank=True, null=True)),
                ('time_finish', models.DateField(blank=True, null=True)),
                ('concept_covered', models.TextField(blank=True, null=True)),
                ('teachers_comment', models.CharField(blank=True, max_length=40, null=True)),
                ('hod', models.CharField(blank=True, max_length=40, null=True)),
                ('head_teacher', models.CharField(blank=True, max_length=40, null=True)),
                ('log_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Logbooks.logbookserial')),
            ],
        ),
    ]
