# Generated by Django 4.0.4 on 2022-10-31 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masomo',
            fields=[
                ('subject_name', models.CharField(help_text='kiswahili-4a-2022', max_length=20, primary_key=True, serialize=False)),
                ('class_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Student.madarasa')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test1', models.CharField(blank=True, default=0, max_length=5, null=True)),
                ('test2', models.CharField(blank=True, default=0, max_length=5, null=True)),
                ('test3', models.CharField(blank=True, default=0, max_length=5, null=True)),
                ('mid', models.CharField(blank=True, default=0, max_length=5, null=True)),
                ('test4', models.CharField(blank=True, default=0, max_length=5, null=True)),
                ('test5', models.CharField(blank=True, default=0, max_length=5, null=True)),
                ('total_test', models.CharField(blank=True, default=0, max_length=5, null=True)),
                ('test_average', models.CharField(blank=True, default=0, max_length=5, null=True)),
                ('term1_exam', models.CharField(blank=True, default=0, max_length=5, null=True)),
                ('total', models.CharField(blank=True, default=0, max_length=5, null=True)),
                ('average', models.CharField(blank=True, default=0, max_length=5, null=True)),
                ('grades', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=5, null=True)),
                ('remarks', models.CharField(blank=True, max_length=5, null=True)),
                ('darasa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Student.madarasa')),
                ('student_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Student.mwanafunzi')),
                ('subject_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Subjects.masomo')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(blank=True, max_length=4, null=True)),
                ('average', models.CharField(blank=True, max_length=4, null=True)),
                ('darasa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Student.madarasa')),
                ('student_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Student.mwanafunzi')),
                ('subj1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Subjects.masomo')),
            ],
        ),
    ]
